# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'NoteBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoteBook
  pod 'SnapKit', '~> 5.0.0'
  pod 'SQLite.swift', '~> 0.13.2'
end
